### ISSUE TITLE
Bugfix, deployment, page render or others

### ISSUE THREAD

**Issue by SmilingWayne** [SmilingWayne/me#5]
- Mainly some bugs during deployment on GitHub.io

**Comment by SmilingWayne** [comment]
2024-07-29: 
- Problems occurred like [This Link](https://github.com/pypa/setuptools/issues/4519) which seem to come from setuptools dependencies update with version 72.0.0.
- Temporal bugfix procedure follows [This repo](https://github.com/simonwhitaker/setuptools-demo/blob/main/.github/workflows/python.yml),  using by force setuptools==71.0.0 and add `--no-build-isolation` command in `pip install` command. see commit <https://github.com/SmilingWayne/me/commit/6cc6aaac1b32322f363e09b15b146d72e743509c>.

2024-08-05:
- with setuptools == 72.1.0 release, bug fixed :), so the temporal fix `--no-build-isolation` is rolled back in commit <https://github.com/SmilingWayne/me/commit/ded0e7357d1257c6ebd7d1d83a0d5e97442f045b> .
- Deployed successfully. ✅

**Comment by SmilingWayne** [comment]
New Problem resolved in Sunday,  Oct 13, 2024 at 0:34. Causes:

1. Yesterday, 2024.10.12, I updated Github workflow,  add Github Robot into  Github Actions. But forgot to set `fetch-depth` to 0 when using actions checkout.

Failed version:

```yml
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
```

This would cause `mkdocs-git-revision-date-localized-plugin` plugin fail to retrieve "file creation time", instead, the "file creation time" would be the same as "Last Update Time", which is the closest commit. Details can be found [here](https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/index.html). 

Success version:

```yml
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
```

The new commit <https://github.com/SmilingWayne/me/commit/6aeacb2836b303966695c9e6902836984418914c> is tested and worked correctly.
